// =====================================================
// LEON.CS - missions/mission_0.js
// Missao: Lógica de Programação e Algoritmos
// =====================================================

const MISSION_0 = {
  id: 0,
  title: 'Lógica de Programação e Algoritmos',
  icon: '🎮',
  free: true,
  desc: 'Em Resident Evil, sobreviver não depende só de armas. Leon precisa pensar antes de agir: decidir para onde ir, qual porta abrir, qual item usar.',
  objs: [
    'Entender o que é lógica de programação e algoritmos',
    'Aprender a pensar como um programador',
  ],
  steps: [
    {
      type: 'mc',
      bubble: 'Agente, em programação usamos <strong>lógica</strong> para tomar decisões corretas, assim como em Resident Evil você precisa escolher o caminho certo para sobreviver.',
      q: 'O que é lógica?',
      hint: 'Pense em resolver problemas com raciocínio',
      opts: [
        { t: 'Pensar de forma organizada para resolver problemas', ok: true },
        { t: 'Um tipo de vírus', ok: false },
        { t: 'Um tipo de computador', ok: false },
        { t: 'Um personagem do jogo', ok: false },
      ],
      exp: 'Lógica é a capacidade de pensar de forma estruturada para encontrar soluções.',
    },
    {
      type: 'mc',
      bubble: 'Imagine que Leon precisa escapar de um corredor cheio de zumbis. Ele precisa seguir alguns passos organizados.',
      q: 'Na programação, como chamamos uma sequência de passos para resolver um problema?',
      hint: 'É como um plano de missão',
      opts: [
        { t: 'Algoritmo', ok: true },
        { t: 'Computador', ok: false },
        { t: 'Monitor', ok: false },
        { t: 'Internet', ok: false },
      ],
      exp: 'Algoritmo é uma sequência de passos organizada para resolver um problema.',
    },
    {
      type: 'mc',
      bubble: 'Um algoritmo é como um plano de sobrevivência em Resident Evil.',
      q: 'Qual dessas opções representa um algoritmo?',
      hint: 'Pense em passos organizados',
      opts: [
        { t: 'Pegar chave → abrir porta → fugir do zumbi', ok: true },
        { t: 'Atirar aleatoriamente', ok: false },
        { t: 'Ficar parado', ok: false },
        { t: 'Desligar o computador', ok: false },
      ],
      exp: 'Um algoritmo sempre possui passos organizados para resolver uma situação.',
    },
    {
      type: 'mc',
      bubble: 'Na programação usamos decisões para escolher ações diferentes.',
      q: 'Quando Leon encontra uma porta trancada, qual seria a decisão lógica?',
      hint: 'Depende se ele tem a chave',
      opts: [
        { t: 'Se tiver chave → abrir porta', ok: true },
        { t: 'Ignorar a porta', ok: false },
        { t: 'Desligar o jogo', ok: false },
        { t: 'Quebrar o computador', ok: false },
      ],
      exp: 'Decisões são baseadas em condições: se algo acontecer, execute determinada ação.',
    },
    {
      type: 'code',
      bubble: 'Veja este pequeno exemplo em C# inspirado em Resident Evil.',
      code: `Console.<span class="mt">WriteLine</span>(<span class="st">"Zumbi detectado!"</span>);`,
      q: 'O que esse código exibirá?',
      hint: 'Veja o texto dentro das aspas',
      opts: [
        { t: 'Zumbi detectado!', ok: true },
        { t: 'Console', ok: false },
        { t: 'WriteLine', ok: false },
        { t: 'Nada', ok: false },
      ],
      exp: 'Console.WriteLine() imprime exatamente o texto que está entre aspas.',
    },
    {
      type: 'code',
      bubble: 'Veja outro código simples:',
      code: `Console.<span class="mt">WriteLine</span>(<span class="st">"Leon encontrou uma chave"</span>);`,
      q: 'O que aparecerá na tela?',
      hint: 'Leia o texto dentro das aspas',
      opts: [
        { t: 'Leon encontrou uma chave', ok: true },
        { t: 'Leon', ok: false },
        { t: 'Chave', ok: false },
        { t: 'Erro', ok: false },
      ],
      exp: 'O método WriteLine imprime o texto exatamente como está entre aspas.',
    },
    {
      type: 'code',
      bubble: 'Observe o código abaixo:',
      code: `Console.<span class="mt">WriteLine</span>(<span class="st">"Missão iniciada"</span>);`,
      q: 'Qual método está sendo usado para exibir texto?',
      hint: 'É o método mais usado para imprimir no console',
      opts: [
        { t: 'WriteLine', ok: true },
        { t: 'Print', ok: false },
        { t: 'Display', ok: false },
        { t: 'Show', ok: false },
      ],
      exp: 'WriteLine é o método usado em C# para imprimir texto no console.',
    },
    {
      type: 'fill',
      bubble: 'Complete o código para mostrar a mensagem "Zumbi eliminado".',
      code: `Console.<span class="kw">_______</span>(<span class="st">"Zumbi eliminado"</span>);`,
      q: 'Qual método exibe texto no console?',
      hint: 'Ele também pula uma linha',
      ans: 'WriteLine',
      exp: 'Console.WriteLine() imprime texto e pula para a próxima linha.',
    },
    {
      type: 'fill',
      bubble: 'Complete o código abaixo:',
      code: `Console.<span class="kw">_______</span>(<span class="st">"Missão concluída"</span>);`,
      q: 'Qual método deve completar o código?',
      hint: 'Exibe texto no console',
      ans: 'WriteLine',
      exp: 'WriteLine é o método padrão para exibir mensagens no console.',
    },
    {
      type: 'fill',
      bubble: 'Complete o código para mostrar a frase "Leon encontrou munição".',
      code: `Console.<span class="kw">_______</span>(<span class="st">"Leon encontrou munição"</span>);`,
      q: 'Qual método imprime texto na tela?',
      hint: 'É usado junto com Console',
      ans: 'WriteLine',
      exp: 'Console.WriteLine() é o método responsável por mostrar texto no console.',
    },
  ],
};
